{
 "title": "Main",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "GeoMap",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"earthWatch-jppytdv\")\n  |> filter(fn: (r) => r[\"_field\"] == \"properties_latitude\" or r[\"_field\"] == \"properties_longitude\" or r[\"_field\"] == \"properties_mag\")"
    }
   ]
  },
  {
   "title": "Max Magnitude",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"earthWatch-jppytdv\")\n  |> filter(fn: (r) => r[\"_field\"] == \"properties_mag\")\n  |> group(columns: [\"host\", \"_measurement\"], mode:\"by\")\n  |> max()"
    }
   ]
  },
  {
   "title": "Total earthquake during period",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"earthWatch-jppytdv\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> group(columns: [\"host\", \"_measurement\"], mode:\"by\")"
    }
   ]
  },
  {
   "title": "Number of reviewed earthquake",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"earthWatch-jppytdv\")\n  |> filter(fn: (r) => r[\"_field\"] == \"properties_status\")"
    }
   ]
  },
  {
   "title": "Earthquakes count evolution (15min interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"earthWatch-jppytdv\", onEmpty: \"drop\")"
    }
   ]
  },
  {
   "title": "Last Earthquakes",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"earthWatch-jppytdv\", onEmpty: \"drop\")"
    }
   ]
  }
 ]
}